// aikido-exl3 Hopper kernels: host side + torch bindings.
//
// y = Had128(x * suh) @ W_hat -> Had128 -> * svh for an EXL3 (ExLlamaV3 trellis) matrix, K = 4 or K = 6,
// fp16 or bf16 at the boundary (the conversions live inside the two Hadamard launches, exl3_had.cuh).
//
// - GEMM: exl3_hopper_template.h = vLLM's Marlin kernel template (Apache-2.0) with the int4 dequant replaced by
//   EXL3's trellis decode (ExLlamaV3, MIT). Host-side launch logic below follows vLLM v0.29.0
//   csrc/libtorch_stable/quantization/marlin/marlin.cu (Apache-2.0, Neural Magic / vLLM project).
// - Hadamards: ExLlamaV3's had_hf_r_128_inner (MIT, Turboderp), vendored unchanged in third_party/exllamav3.
//
// Decoded weights are bit-identical to exllamav3_ext.reconstruct; only the accumulation order differs.

#define MARLIN_NAMESPACE_NAME aikido_exl3_marlin

#include <torch/extension.h>
#include <c10/cuda/CUDAGuard.h>
#include <ATen/cuda/CUDAContext.h>
#include <cuda.h>
#include <cuda_fp16.h>
#include <cuda_runtime.h>
#include <climits>
#include <map>
#include <vector>
#include <tuple>

#include "exl3_hopper_kernels.h"
#include "exl3_had.cuh"

static void had_out_launch(void* y, bool y_bf16, const half* svh, int rows, int n, cudaStream_t stream);
static void had_in_launch(const void* x, bool x_bf16, half* xh, const half* suh, int shards, int rows, int k,
                          cudaStream_t stream);

namespace MARLIN_NAMESPACE_NAME {

// Variants compiled into this build: AIKIDO_VARIANTS(X) = X(mb, cb, kb) ... (header generated by setup.py)
#include "aikido_families.h"

#define AIKIDO_SEL(threads_, tn_, tk_, mb_, cb_, kb_)                                            \
  if (threads == threads_ && tn == tn_ && tk == tk_ && mb == mb_ && cb == cb_ && kb == kb_)      \
    return AIKIDO_KERNEL(threads_, tn_, tk_, mb_, cb_, kb_);
#define AIKIDO_SEL_VARIANT(mb, cb, kb) AIKIDO_THREAD_CFGS(AIKIDO_SEL, mb, cb, kb)

static FuncPtr select_kernel(int threads, int tn, int tk, int mb, int cb, int kb) {
  AIKIDO_VARIANTS(AIKIDO_SEL_VARIANT)
  return nullptr;
}

struct ThreadCfg {
  int thread_k, thread_n, num_threads;
};

// Same tables and priority as Marlin.
static const ThreadCfg small_cfgs[] = {{128, 128, 256}, {64, 128, 128}, {128, 64, 128}};
static const ThreadCfg large_cfgs[] = {{64, 256, 256}, {64, 128, 128}, {128, 64, 128}};

// kb = EXL3 bits per weight; K = 6 is staged like Marlin's 8-bit weights (two 16-byte vectors per lane).
static int kernel_cache_size(const ThreadCfg& c, int thread_m_blocks, int kb) {
  int tb_k = c.thread_k, tb_n = c.thread_n, tb_m = thread_m_blocks * 16;
  int sh_a_size = kStages * (tb_m * tb_k) * 2;
  int sh_b_size = kStages * (tb_k * tb_n / (kb == 4 ? 8 : 4)) * 4;
  int sh_red_size = tb_m * (tb_n + 8) * 2;
  int sh_bias_size = tb_n * 2;
  int tmp_size = (sh_b_size > sh_red_size ? sh_red_size : sh_b_size) + sh_bias_size;
  tmp_size = std::max(std::max(sh_b_size, sh_red_size), tmp_size);
  int sh_s_size = tb_n * 2 * kStages;
  return tmp_size + sh_a_size + sh_s_size;
}

static bool valid_cfg(const ThreadCfg& c, int thread_m_blocks, int n, int k, int kb, int max_shared_mem,
                      const std::vector<int64_t>& shard_ends = {}) {
  if (k % c.thread_k != 0 || n % c.thread_n != 0) return false;
  for (int64_t e : shard_ends)  // a column slice (thread_n wide) must not straddle two shards
    if (e % c.thread_n != 0) return false;
  return kernel_cache_size(c, thread_m_blocks, kb) <= max_shared_mem;
}

static constexpr int kMaxBlocksPerSm = 4;
static int g_blocks_per_sm = 1;  // tuning knob (set_blocks_per_sm); Marlin uses 1
static bool g_out_had_inlaunch = true;  // knob (set_out_had_inlaunch): output transform inside the GEMM launch
static int g_debug_flags = 0;           // timing probes only (set_debug_flags): 4 = kernels return immediately
static bool g_in_had_inlaunch = false;  // knob (set_in_had_inlaunch): input transform as a prologue of a COOPERATIVE
                                        // GEMM launch (grid barrier); experimental

struct DevState {
  int sms = 0;
  int max_shared_mem = 0;
  at::Tensor locks;  // int32 [sms], zero
  at::Tensor c_tmp;  // float [sms * 64 * 256]
};

static DevState& dev_state(int device) {
  static std::map<int, DevState> states;
  auto it = states.find(device);
  if (it != states.end()) return it->second;
  DevState st;
  cudaDeviceGetAttribute(&st.sms, cudaDevAttrMultiProcessorCount, device);
  cudaDeviceGetAttribute(&st.max_shared_mem, cudaDevAttrMaxSharedMemoryPerBlockOptin, device);
  TORCH_CHECK(st.sms > 0 && st.max_shared_mem > 0, "aikido_exl3: device query failed");
  auto dev = at::Device(at::kCUDA, device);
  st.locks = at::zeros({st.sms * kMaxBlocksPerSm}, at::TensorOptions().dtype(at::kInt).device(dev));
  st.c_tmp = at::empty({(int64_t)st.sms * kMaxBlocksPerSm * 64 * 256}, at::TensorOptions().dtype(at::kFloat).device(dev));
  states[device] = st;
  return states[device];
}

// GEMM on a pre-rotated input. a: fp16 [m, k] contiguous; b: repacked trellis; c: fp16 [m, n].
//
// Multi-matrix: `shard_ends` (ascending column ends of all shards but the last, at most 3) splits n; shard s reads
// the input slab a_ptr + s * prob_m * prob_k. Every shard width must be a multiple of the chosen thread_n.
//
// svh != nullptr: also apply the output transform c = Had128(c) * svh (c as bf16 bits if out_bf16). It runs inside the
// GEMM launch (the block that writes a column slice transforms it in shared memory first) whenever thread_n is a
// multiple of 128, else as a separate launch. Both give the same bits.
static void gemm_launch(const half* a_ptr, const void* b_ptr, half* c_ptr, int prob_m, int prob_n, int prob_k,
                        int cb, int kb, int device, cudaStream_t stream, int force_thread_k, int force_thread_n,
                        const std::vector<int64_t>& shard_ends = {}, const half* svh = nullptr,
                        bool out_bf16 = false, const void* x_raw = nullptr, bool x_bf16 = false,
                        const half* suh = nullptr) {
  // x_raw != nullptr: a_ptr is scratch and must first receive Had128(fp16(x_raw) * suh[s]) per shard: inside the
  // launch (cooperative launch, grid barrier) if enabled and the rows fit one launch, else as its own launch.
  const int in_shards = (int)shard_ends.size() + 1;
  bool in_inlaunch = x_raw && g_in_had_inlaunch && prob_m <= 64;
  if (x_raw && !in_inlaunch) had_in_launch(x_raw, x_bf16, (half*)a_ptr, suh, in_shards, prob_m, prob_k, stream);
  TORCH_CHECK(shard_ends.size() <= 3, "aikido_exl3: at most 4 shards");
  int se[3] = {INT_MAX, INT_MAX, INT_MAX};
  for (size_t i = 0; i < shard_ends.size(); i++) se[i] = (int)shard_ends[i];
  const int a_shard_stride = shard_ends.empty() ? 0 : prob_m * (prob_k / 8);
  DevState& st = dev_state(device);
  const int4* A_ptr = (const int4*)a_ptr;
  const int4* B_ptr = (const int4*)b_ptr;
  int4* C_ptr = (int4*)c_ptr;
  int4* C_tmp_ptr = (int4*)st.c_tmp.data_ptr();
  int* locks = (int*)st.locks.data_ptr();
  int lda = prob_k;
  int sms = st.sms;
  int max_shared_mem = st.max_shared_mem;

  int max_par = 16;
  if (prob_n <= 4096) max_par = 16 * 8;
  int rest_m = prob_m;
  int max_thread_m_blocks = 4;
  while (rest_m) {
    int par_count = rest_m / (max_thread_m_blocks * 16);
    if (par_count > max_par) par_count = max_par;
    int prob_m_split = par_count > 0 ? (par_count * (max_thread_m_blocks * 16)) : rest_m;
    int thread_m_blocks = std::min((prob_m_split + 15) / 16, max_thread_m_blocks);
    bool m8 = prob_m_split <= 8;

    ThreadCfg cfg{-1, -1, -1};
    if (force_thread_k > 0 && force_thread_n > 0) {
      cfg = ThreadCfg{force_thread_k, force_thread_n,
                      (force_thread_k == 64 && force_thread_n == 128) || (force_thread_k == 128 && force_thread_n == 64)
                          ? 128 : 256};
      TORCH_CHECK(valid_cfg(cfg, thread_m_blocks, prob_n, prob_k, kb, max_shared_mem - 512), "aikido_exl3: bad forced config");
    } else {
      const ThreadCfg* cfgs = thread_m_blocks > 1 ? large_cfgs : small_cfgs;
      for (int i = 0; i < 3; i++) {
        if (!valid_cfg(cfgs[i], thread_m_blocks, prob_n, prob_k, kb, max_shared_mem - 512, shard_ends)) continue;
        cfg = cfgs[i];
        break;
      }
      if (cfg.thread_n != -1) {
        if (prob_n / cfg.thread_n * ((prob_m_split + thread_m_blocks * 16 - 1) / (thread_m_blocks * 16)) * 4 <= sms) {
          ThreadCfg narrow{128, 64, 128};
          if (valid_cfg(narrow, thread_m_blocks, prob_n, prob_k, kb, max_shared_mem, shard_ends)) cfg = narrow;
        }
      }
      if (cfg.thread_k == -1 && max_thread_m_blocks > 1) {
        max_thread_m_blocks--;
        continue;
      }
    }
    TORCH_CHECK(cfg.thread_k != -1, "aikido_exl3: no thread config for m=", prob_m, " k=", prob_k, " n=", prob_n);

    FuncPtr kernel = select_kernel(cfg.num_threads, cfg.thread_n, cfg.thread_k, m8 ? 0 : thread_m_blocks, cb, kb);
    for (size_t i = 0; i < shard_ends.size(); i++)
      TORCH_CHECK(shard_ends[i] % cfg.thread_n == 0, "aikido_exl3: shard end ", shard_ends[i],
                  " is not a multiple of thread_n = ", cfg.thread_n);
    TORCH_CHECK(kernel != nullptr, "aikido_exl3: kernel not compiled: threads=", cfg.num_threads,
                " thread_n=", cfg.thread_n, " thread_k=", cfg.thread_k, " m_blocks=", thread_m_blocks, " cb=", cb, " K=", kb);

    int bps = g_blocks_per_sm;
    int smem = bps > 1 ? max_shared_mem / bps - 1024 : max_shared_mem;
    TORCH_CHECK(kernel_cache_size(cfg, thread_m_blocks, kb) <= smem, "aikido_exl3: shared memory too small for ", bps,
                " blocks per SM");
    cudaFuncSetAttribute(kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, smem);
    // clang-format off
    const int out_flags = (svh && g_out_had_inlaunch && cfg.thread_n % 128 == 0) ? (1 | (out_bf16 ? 2 : 0)) : 0;
    if (in_inlaunch) {
      // cooperative launch: arguments by address, in kernel parameter order (AIKIDO_KERNEL_PARAMS)
      const int4* a_bias = (const int4*)svh; const float* a_fnull = nullptr; const int4* a_inull = nullptr;
      const int* a_gidx = nullptr; int a_zero = 0; bool a_false = false, a_true = true;
      const int4* a_x = (const int4*)x_raw; const int4* a_suh = (const int4*)suh;
      int a_inflags = 1 | (x_bf16 ? 2 : 0), a_shards = in_shards, a_outflags = out_flags, a_smem = smem;
      void* args[] = {&A_ptr, &B_ptr, &C_ptr, &C_tmp_ptr, &a_bias, &a_fnull, &a_inull, &a_fnull, &a_inull, &a_gidx,
                      &a_zero, &prob_m_split, &prob_n, &prob_k, &lda, &locks, &a_false, &a_false, &a_true, &a_smem,
                      (void*)&a_shard_stride, &se[0], &se[1], &se[2], &a_outflags, &a_x, &a_suh, &a_inflags,
                      &a_shards};
      cudaLaunchCooperativeKernel((void*)kernel, sms * bps, cfg.num_threads, args, smem, stream);
    } else {
      kernel<<<sms * bps, cfg.num_threads, smem, stream>>>(
          A_ptr, B_ptr, C_ptr, C_tmp_ptr, (const int4*)svh, nullptr, nullptr, nullptr, nullptr, nullptr, 0,
          prob_m_split, prob_n, prob_k, lda, locks, false, false, true, smem,
          a_shard_stride, se[0], se[1], se[2], out_flags, nullptr, nullptr, g_debug_flags, 1);
    }
    // clang-format on
    if (svh && !out_flags) ::had_out_launch((void*)C_ptr, out_bf16, svh, prob_m_split, prob_n, stream);

    A_ptr += prob_m_split * (lda / 8);
    C_ptr += prob_m_split * (prob_n / 8);
    rest_m -= prob_m_split;
  }
}

}  // namespace MARLIN_NAMESPACE_NAME

// ---------------------------------------------------------------------------------------------------------------
// Hadamard launches (ExLlamaV3's arithmetic, exl3_had.cuh; bf16 <-> fp16 conversion at the boundary when asked)

// Block (x, y) transforms the 128-block y of output row x. Input row = x % rows, scale vector = x / rows:
//  - input transform of a fused group: grid (shards * rows, k / 128), slab s (rows x k) = Had128(x * suh[s]);
//  - single matrix / output transform: grid (rows, cols / 128), `rows` = all rows.
// in_stride / out_stride: elements per row of the input / output buffer (>= the transformed width gridDim.y * 128;
// larger when the output is a column span of a wider fused tensor).
static constexpr float kHadScale = 0.088388347648f;  // 1/sqrt(128)

// WARPS: 128-blocks per thread block (1 warp each; the transform only shuffles inside a warp). 8 = one 256-thread block
// per 8 consecutive 128-blocks of a row (many-row path: 8x fewer thread blocks to schedule), 1 = a 32-thread block per
// 128-block (decode: the launch is pure launch cost either way).
template <bool in_bf16, bool out_bf16, bool pre_scale, bool post_scale, int WARPS>
__global__ __launch_bounds__(32 * WARPS)
void aikido_had_r_128_kernel(const half* __restrict__ input_ptr, half* __restrict__ output_ptr,
                             const half* __restrict__ scales, const int rows, const float r_scale,
                             const size_t in_stride, const size_t out_stride) {
  const size_t width = (size_t)gridDim.y * 128 * WARPS;
  const size_t blk = (size_t)blockIdx.y * WARPS + threadIdx.x / 32;
  input_ptr += in_stride * (blockIdx.x % rows) + blk * 128;
  output_ptr += out_stride * blockIdx.x + blk * 128;
  aikido_had_r_128_inner<in_bf16, out_bf16, pre_scale, post_scale>(
      input_ptr, output_ptr, scales + width * (blockIdx.x / rows), (int)blk * 32, r_scale);
}

static int g_had_warps = 8;  // knob (set_had_warps): 128-blocks per thread block on the many-row path (1 or 8)
static constexpr int kHadWarpsMinRows = 32;

#define AIKIDO_HAD_LAUNCH(IN, OUT, PRE, POST, in, out, sc, rows_, nblk, grid_x, in_stride, out_stride)                   \
  if (g_had_warps == 8 && (nblk) % 8 == 0 && (rows_) >= kHadWarpsMinRows)                                                  \
    aikido_had_r_128_kernel<IN, OUT, PRE, POST, 8><<<dim3(grid_x, (nblk) / 8), 256, 0, stream>>>(                         \
        in, out, sc, rows_, kHadScale, in_stride, out_stride);                                                             \
  else                                                                                                                     \
    aikido_had_r_128_kernel<IN, OUT, PRE, POST, 1><<<dim3(grid_x, nblk), 32, 0, stream>>>(                                 \
        in, out, sc, rows_, kHadScale, in_stride, out_stride)


// xh[s] = Had128(fp16(x) * suh[s]) for s < shards. x: fp16 or bf16 bits [rows, k]; xh: fp16 [shards * rows, k].
static void had_in_launch(const void* x, bool x_bf16, half* xh, const half* suh, int shards, int rows, int k,
                          cudaStream_t stream) {
  if (x_bf16) {
    AIKIDO_HAD_LAUNCH(true, false, true, false, (const half*)x, xh, suh, rows, k / 128, shards * rows, (size_t)k, (size_t)k);
  } else {
    AIKIDO_HAD_LAUNCH(false, false, true, false, (const half*)x, xh, suh, rows, k / 128, shards * rows, (size_t)k, (size_t)k);
  }
}

// out = Had128(y) * svh; y: fp16 [rows, n] (row stride n); out: fp16 or bf16 bits, row stride out_stride (out == y
// with out_stride == n is the in-place form; a larger stride writes a column span of a wider fused output).
static void had_out_launch_to(const void* y, void* out, size_t out_stride, bool out_bf16, const half* svh, int rows,
                              int n, cudaStream_t stream) {
  if (out_bf16) {
    AIKIDO_HAD_LAUNCH(false, true, false, true, (const half*)y, (half*)out, svh, rows, n / 128, rows, (size_t)n, out_stride);
  } else {
    AIKIDO_HAD_LAUNCH(false, false, false, true, (const half*)y, (half*)out, svh, rows, n / 128, rows, (size_t)n, out_stride);
  }
}

// y = Had128(y) * svh in place; y holds fp16 bits on entry and fp16 or bf16 bits on exit.
static void had_out_launch(void* y, bool y_bf16, const half* svh, int rows, int n, cudaStream_t stream) {
  had_out_launch_to(y, y, (size_t)n, y_bf16, svh, rows, n, stream);
}

// ---------------------------------------------------------------------------------------------------------------
// Torch entry points

// -> EXL3 bits per weight of a repacked trellis: [k/16, n/64, 32, 4] = K 4, [k/16, n/64, 32, 4, 2] = K 6
static int kbits_from_trellis_check(const at::Tensor& b, int64_t k, int64_t n) {
  TORCH_CHECK(b.is_cuda() && b.is_contiguous(), "repacked trellis must be a contiguous CUDA tensor");
  TORCH_CHECK(b.dtype() == at::kInt, "repacked trellis must be int32 (use repack_trellis)");
  TORCH_CHECK((b.dim() == 4 || (b.dim() == 5 && b.size(4) == 2)) && b.size(2) == 32 && b.size(3) == 4,
              "repacked trellis must be [k/16, n/64, 32, 4] (K=4) or [k/16, n/64, 32, 4, 2] (K=6)");
  TORCH_CHECK(b.size(0) * 16 == k && b.size(1) * 64 == n, "repacked trellis shape does not match k, n");
  return b.dim() == 4 ? 4 : 6;
}

static bool is_16bit_float(const at::Tensor& t) { return t.dtype() == at::kHalf || t.dtype() == at::kBFloat16; }

// EXL3 trellis int16 [k/16, n/16, 16K] -> lane-major int32.
//
// K = 4 -> [k/16, n/64, 32, 4]: pure permutation of the 32-bit stream words: word l of tile (i, 4g + j) moves to
// [i, g, l, j], so one 16-byte vector holds lane l's stream word for the 4 adjacent n-tiles of a warp (= Marlin's
// 4-bit B indexing).
//
// K = 6 -> [k/16, n/64, 32, 4, 2]: a tile is 48 stream words = 1536 bits, bit 0 = MSB of word 0 (research/04 1.4).
// Lane l decodes positions 8l..8l+7 = windows reaching from bit 48l - 10 to 48l + 48, which straddle 2-3 stream
// words at lane-dependent offsets. Entry [i, g, l, j] = (hi, lo) = the 64 stream bits [48l - 16, 48l + 48) of tile
// (i, 4g + j), tail-biting (= Marlin's 8-bit B indexing: two vectors per lane, ints 2j, 2j+1 belong to n-tile j).
// A lossless bit re-layout: every stream bit is kept, the 16 bits before each lane's own 48 are stored twice
// (8 bits per weight resident instead of 6). `unpack_trellis` inverts it exactly.
at::Tensor repack_trellis(const at::Tensor& trellis) {
  TORCH_CHECK(trellis.dim() == 3 && trellis.dtype() == at::kShort, "trellis must be int16 [k/16, n/16, 16K]");
  TORCH_CHECK(trellis.size(2) == 64 || trellis.size(2) == 96, "only K = 4 and K = 6 are supported");
  TORCH_CHECK(trellis.size(1) % 8 == 0 && trellis.size(0) % 8 == 0, "k and n must be multiples of 128");
  int64_t kt = trellis.size(0), nt = trellis.size(1);
  if (trellis.size(2) == 64) {
    auto w = trellis.contiguous().view(at::kInt);  // [kt, nt, 32], little-endian uint16 pairs (as ExLlamaV3 reads it)
    return w.view({kt, nt / 4, 4, 32}).permute({0, 1, 3, 2}).contiguous();
  }
  auto opts_l = at::TensorOptions().dtype(at::kLong).device(trellis.device());
  std::vector<int64_t> q0(32), q1(32), q2(32), odd(32);
  for (int l = 0; l < 32; l++) {
    int s = (48 * l - 16 + 1536) % 1536;  // first stored bit; s % 32 == 0 for odd lanes, 16 for even lanes
    q0[l] = s / 32; q1[l] = (s / 32 + 1) % 48; q2[l] = (s / 32 + 2) % 48; odd[l] = l & 1;
  }
  auto i0 = at::tensor(q0, opts_l), i1 = at::tensor(q1, opts_l), i2 = at::tensor(q2, opts_l);
  auto is_odd = at::tensor(odd, opts_l).to(at::kBool);
  auto out = at::empty({kt, nt / 4, 32, 4, 2}, at::TensorOptions().dtype(at::kInt).device(trellis.device()));
  const int64_t chunk = 16;
  for (int64_t r0 = 0; r0 < kt; r0 += chunk) {
    int64_t r1 = std::min(kt, r0 + chunk);
    auto w = trellis.slice(0, r0, r1).contiguous().view(at::kInt).to(at::kLong).bitwise_and(0xffffffffLL);  // [c, nt, 48]
    auto x0 = w.index_select(2, i0), x1 = w.index_select(2, i1), x2 = w.index_select(2, i2);               // [c, nt, 32]
    auto hi = at::where(is_odd, x0, x0.bitwise_left_shift(16).bitwise_or(x1.bitwise_right_shift(16)).bitwise_and(0xffffffffLL));
    auto lo = at::where(is_odd, x1, x1.bitwise_left_shift(16).bitwise_or(x2.bitwise_right_shift(16)).bitwise_and(0xffffffffLL));
    auto both = at::stack({hi, lo}, 3);                                   // [c, nt, 32, 2], values 0 .. 2^32-1
    both = at::where(both.ge(0x80000000LL), both - 0x100000000LL, both).to(at::kInt);
    out.slice(0, r0, r1).copy_(both.view({r1 - r0, nt / 4, 4, 32, 2}).permute({0, 1, 3, 2, 4}));
  }
  return out;
}

// Inverse of repack_trellis (parity only). K = 6: the stream is rebuilt from each lane's own 48 bits.
at::Tensor unpack_trellis(const at::Tensor& b) {
  TORCH_CHECK((b.dim() == 4 || b.dim() == 5) && b.dtype() == at::kInt);
  int64_t kt = b.size(0), g = b.size(1);
  if (b.dim() == 4) return b.permute({0, 1, 3, 2}).contiguous().view({kt, g * 4, 32}).view(at::kShort);
  auto out = at::empty({kt, g * 4, 48}, at::TensorOptions().dtype(at::kInt).device(b.device()));
  const int64_t chunk = 16;
  for (int64_t r0 = 0; r0 < kt; r0 += chunk) {
    int64_t r1 = std::min(kt, r0 + chunk), c = r1 - r0;
    auto t = b.slice(0, r0, r1).permute({0, 1, 3, 2, 4}).reshape({c, g * 4, 32, 2}).to(at::kLong).bitwise_and(0xffffffffLL);
    auto own = t.select(3, 0).bitwise_and(0xffffLL).bitwise_left_shift(32).bitwise_or(t.select(3, 1));  // [c, nt, 32] 48 bits
    auto pair = own.view({c, g * 4, 16, 2});
    auto e = pair.select(3, 0), o = pair.select(3, 1);                       // lanes 2v, 2v+1 own words 3v, 3v+1, 3v+2
    auto w0 = e.bitwise_right_shift(16);
    auto w1 = e.bitwise_and(0xffffLL).bitwise_left_shift(16).bitwise_or(o.bitwise_right_shift(32));
    auto w2 = o.bitwise_and(0xffffffffLL);
    auto w = at::stack({w0, w1, w2}, 3).view({c, g * 4, 48});
    w = at::where(w.ge(0x80000000LL), w - 0x100000000LL, w).to(at::kInt);
    out.slice(0, r0, r1).copy_(w);
  }
  return out.view(at::kShort);
}

// c = a @ W_hat (rotated basis, no Hadamards). a fp16 [m, k], c fp16 [m, n].
void exl3_gemm_hopper(const at::Tensor& a, const at::Tensor& b, at::Tensor& c, int64_t cb, int64_t thread_k,
                      int64_t thread_n) {
  const at::cuda::OptionalCUDAGuard device_guard(a.device());
  TORCH_CHECK(a.dim() == 2 && c.dim() == 2 && a.dtype() == at::kHalf && c.dtype() == at::kHalf);
  TORCH_CHECK(a.is_contiguous() && c.is_contiguous());
  int64_t m = a.size(0), k = a.size(1), n = c.size(1);
  TORCH_CHECK(c.size(0) == m);
  int kb = kbits_from_trellis_check(b, k, n);
  if (m == 0) return;
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  aikido_exl3_marlin::gemm_launch((const half*)a.data_ptr(), b.data_ptr(), (half*)c.data_ptr(), (int)m, (int)n, (int)k,
                                  (int)cb, kb, a.get_device(), stream, (int)thread_k, (int)thread_n);
}

// Rotated-basis GEMM of a fused group: a_all fp16 [shards * m, k] (slab s = rows s*m .. s*m+m-1), c [m, n_total].
void exl3_gemm_hopper_multi(const at::Tensor& a_all, const at::Tensor& b, at::Tensor& c,
                            std::vector<int64_t> shard_ends, int64_t cb) {
  const at::cuda::OptionalCUDAGuard device_guard(a_all.device());
  TORCH_CHECK(a_all.dim() == 2 && c.dim() == 2 && a_all.dtype() == at::kHalf && c.dtype() == at::kHalf);
  TORCH_CHECK(a_all.is_contiguous() && c.is_contiguous());
  int64_t shards = (int64_t)shard_ends.size() + 1, m = c.size(0), k = a_all.size(1), n = c.size(1);
  TORCH_CHECK(a_all.size(0) == shards * m);
  int kb = kbits_from_trellis_check(b, k, n);
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  aikido_exl3_marlin::gemm_launch((const half*)a_all.data_ptr(), b.data_ptr(), (half*)c.data_ptr(), (int)m, (int)n,
                                  (int)k, (int)cb, kb, a_all.get_device(), stream, -1, -1, shard_ends);
}

// out = Had128(in * scale) (pre = true) or Had128(in) * scale (pre = false); in place allowed.
// in / out may be fp16 or bf16 (pre: bf16 -> fp16 on load; post: fp16 -> bf16 on store; see exl3_had.cuh).
void had_r_128_hopper(const at::Tensor& in, at::Tensor& out, const at::Tensor& scale, bool pre) {
  const at::cuda::OptionalCUDAGuard device_guard(in.device());
  TORCH_CHECK(in.dim() == 2 && is_16bit_float(in) && is_16bit_float(out) && scale.dtype() == at::kHalf);
  TORCH_CHECK(in.size(1) % 128 == 0 && scale.numel() == in.size(1) && in.is_contiguous() && out.is_contiguous());
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  if (pre) {
    TORCH_CHECK(out.dtype() == at::kHalf, "input transform writes fp16");
    had_in_launch(in.data_ptr(), in.dtype() == at::kBFloat16, (half*)out.data_ptr(), (const half*)scale.data_ptr(), 1,
                  (int)in.size(0), (int)in.size(1), stream);
  } else {
    // the transform reads fp16 bits and works in place; a bf16 `in` is only legal as the in-place buffer itself
    TORCH_CHECK(in.dtype() == at::kHalf || in.data_ptr() == out.data_ptr(), "output transform reads fp16");
    if (in.data_ptr() != out.data_ptr()) out.view(at::kHalf).copy_(in);
    had_out_launch(out.data_ptr(), out.dtype() == at::kBFloat16, (const half*)scale.data_ptr(), (int)in.size(0),
                   (int)in.size(1), stream);
  }
}

// Many-row (prefill) building blocks: the two transforms around a dense GEMM on the decoded weight.
// xh[s] = Had128(fp16(x) * suh_cat[s]) for every shard s in ONE launch. x fp16 | bf16 [rows, k], xh fp16 [shards * rows, k].
void had_in_group_hopper(const at::Tensor& x, at::Tensor& xh, const at::Tensor& suh_cat) {
  const at::cuda::OptionalCUDAGuard device_guard(x.device());
  TORCH_CHECK(x.dim() == 2 && is_16bit_float(x) && x.is_contiguous() && x.size(1) % 128 == 0);
  int64_t rows = x.size(0), k = x.size(1);
  TORCH_CHECK(suh_cat.dtype() == at::kHalf && suh_cat.is_contiguous() && suh_cat.numel() % k == 0);
  int64_t shards = suh_cat.numel() / k;
  TORCH_CHECK(xh.dtype() == at::kHalf && xh.is_contiguous() && xh.numel() >= shards * rows * k);
  if (rows == 0) return;
  had_in_launch(x.data_ptr(), x.dtype() == at::kBFloat16, (half*)xh.data_ptr(), (const half*)suh_cat.data_ptr(),
                (int)shards, (int)rows, (int)k, at::cuda::getCurrentCUDAStream().stream());
}

// out[:, col0 : col0 + n] = Had128(y) * svh, stored in out's dtype (fp16 | bf16). y fp16 [rows, n] contiguous;
// out [rows, n_total] contiguous: the result goes straight into its column span, no temporary, no cast launch.
void had_out_into_hopper(const at::Tensor& y, const at::Tensor& svh, at::Tensor& out, int64_t col0) {
  const at::cuda::OptionalCUDAGuard device_guard(y.device());
  TORCH_CHECK(y.dim() == 2 && y.dtype() == at::kHalf && y.is_contiguous() && y.size(1) % 128 == 0);
  TORCH_CHECK(out.dim() == 2 && is_16bit_float(out) && out.is_contiguous() && out.size(0) == y.size(0));
  TORCH_CHECK(col0 >= 0 && col0 + y.size(1) <= out.size(1));
  TORCH_CHECK(svh.dtype() == at::kHalf && svh.is_contiguous() && svh.numel() == y.size(1));
  if (y.size(0) == 0) return;
  had_out_launch_to(y.data_ptr(), (char*)out.data_ptr() + 2 * col0, (size_t)out.size(1), out.dtype() == at::kBFloat16,
                    (const half*)svh.data_ptr(), (int)y.size(0), (int)y.size(1), at::cuda::getCurrentCUDAStream().stream());
}

// y = Had(x * suh) @ W_hat -> Had -> * svh.  Writes into `y`, uses caller-owned scratch `xh` (fp16, >= m * k).
// x and y are fp16 or bf16 independently; the GEMM itself always runs on fp16 (ExLlamaV3 semantics). With bf16 the
// result equals `f(x.to(fp16)).to(bf16)` bit for bit: the conversions are torch's value conversions.
void exl3_linear_hopper_out(const at::Tensor& x, const at::Tensor& b, const at::Tensor& suh, const at::Tensor& svh,
                            int64_t cb, at::Tensor& xh, at::Tensor& y) {
  const at::cuda::OptionalCUDAGuard device_guard(x.device());
  TORCH_CHECK(x.dim() == 2 && is_16bit_float(x) && x.is_contiguous());
  int64_t m = x.size(0), k = x.size(1), n = y.size(1);
  int kb = kbits_from_trellis_check(b, k, n);
  TORCH_CHECK(xh.dtype() == at::kHalf && xh.numel() >= m * k && xh.is_contiguous());
  TORCH_CHECK(is_16bit_float(y) && y.dim() == 2 && y.size(0) == m && y.is_contiguous());
  TORCH_CHECK(suh.numel() == k && svh.numel() == n && suh.dtype() == at::kHalf && svh.dtype() == at::kHalf);
  TORCH_CHECK(suh.is_contiguous() && svh.is_contiguous());
  if (m == 0) return;
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  aikido_exl3_marlin::gemm_launch((const half*)xh.data_ptr(), b.data_ptr(), (half*)y.data_ptr(), (int)m, (int)n, (int)k,
                                  (int)cb, kb, x.get_device(), stream, -1, -1, {}, (const half*)svh.data_ptr(),
                                  y.dtype() == at::kBFloat16, x.data_ptr(), x.dtype() == at::kBFloat16,
                                  (const half*)suh.data_ptr());
}

// Fused group (same input, same k, same K/codebook): b = repacked trellises concatenated along dim 1,
// suh_cat [shards, k], svh_cat [n_total], shard_ends = column ends of all shards but the last.
// xh: scratch fp16 >= shards * m * k.  y: [m, n_total], fp16 or bf16 (as x).
void exl3_linear_hopper_multi_out(const at::Tensor& x, const at::Tensor& b, const at::Tensor& suh_cat,
                                  const at::Tensor& svh_cat, std::vector<int64_t> shard_ends, int64_t cb,
                                  at::Tensor& xh, at::Tensor& y) {
  const at::cuda::OptionalCUDAGuard device_guard(x.device());
  TORCH_CHECK(x.dim() == 2 && is_16bit_float(x) && x.is_contiguous());
  int64_t m = x.size(0), k = x.size(1), n = y.size(1), shards = (int64_t)shard_ends.size() + 1;
  int kb = kbits_from_trellis_check(b, k, n);
  TORCH_CHECK(xh.dtype() == at::kHalf && xh.numel() >= shards * m * k && xh.is_contiguous());
  TORCH_CHECK(is_16bit_float(y) && y.dim() == 2 && y.size(0) == m && y.is_contiguous());
  TORCH_CHECK(suh_cat.dtype() == at::kHalf && suh_cat.is_contiguous() && suh_cat.numel() == shards * k);
  TORCH_CHECK(svh_cat.dtype() == at::kHalf && svh_cat.numel() == n && svh_cat.is_contiguous());
  if (m == 0) return;
  cudaStream_t stream = at::cuda::getCurrentCUDAStream().stream();
  aikido_exl3_marlin::gemm_launch((const half*)xh.data_ptr(), b.data_ptr(), (half*)y.data_ptr(), (int)m, (int)n, (int)k,
                                  (int)cb, kb, x.get_device(), stream, -1, -1, shard_ends,
                                  (const half*)svh_cat.data_ptr(), y.dtype() == at::kBFloat16, x.data_ptr(),
                                  x.dtype() == at::kBFloat16, (const half*)suh_cat.data_ptr());
}

at::Tensor exl3_linear_hopper(const at::Tensor& x, const at::Tensor& b, const at::Tensor& suh, const at::Tensor& svh,
                              int64_t cb) {
  auto xh = at::empty(x.sizes(), x.options().dtype(at::kHalf));
  auto y = at::empty({x.size(0), b.size(1) * 64}, x.options());
  exl3_linear_hopper_out(x, b, suh, svh, cb, xh, y);
  return y;
}

void init_device(int64_t device) { aikido_exl3_marlin::dev_state((int)device); }

void set_out_had_inlaunch(bool on) { aikido_exl3_marlin::g_out_had_inlaunch = on; }
void set_had_warps(int64_t w) { TORCH_CHECK(w == 1 || w == 8); g_had_warps = (int)w; }
void set_in_had_inlaunch(bool on) { aikido_exl3_marlin::g_in_had_inlaunch = on; }
void set_debug_flags(int64_t f) { aikido_exl3_marlin::g_debug_flags = (int)f; }

void set_blocks_per_sm(int64_t n) {
  TORCH_CHECK(n >= 1 && n <= aikido_exl3_marlin::kMaxBlocksPerSm);
  aikido_exl3_marlin::g_blocks_per_sm = (int)n;
}

std::vector<int64_t> device_info(int64_t device) {
  auto& st = aikido_exl3_marlin::dev_state((int)device);
  int occ = -1;
  auto kernel = aikido_exl3_marlin::select_kernel(256, 128, 128, 0, 2, 4);
  if (kernel) cudaOccupancyMaxActiveBlocksPerMultiprocessor(&occ, kernel, 256, 0);
  return {st.sms, st.max_shared_mem, occ};
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("repack_trellis", &repack_trellis, "EXL3 trellis -> lane-major layout (K=4: word permutation; K=6: lossless bit re-layout)");
  m.def("unpack_trellis", &unpack_trellis, "inverse of repack_trellis");
  m.def("exl3_gemm_hopper", &exl3_gemm_hopper, "rotated-basis GEMM", py::arg("a"), py::arg("b"), py::arg("c"),
        py::arg("cb"), py::arg("thread_k") = -1, py::arg("thread_n") = -1);
  m.def("exl3_gemm_hopper_multi", &exl3_gemm_hopper_multi, "rotated-basis GEMM of a fused group");
  m.def("had_r_128_hopper", &had_r_128_hopper, "blockwise 128-point Hadamard with pre or post scale");
  m.def("had_in_group_hopper", &had_in_group_hopper, "input transform of a fused group, all shards in one launch (fp16 | bf16 in)");
  m.def("had_out_into_hopper", &had_out_into_hopper, "output transform written into a column span of a wider fp16 | bf16 tensor");
  m.def("exl3_linear_hopper_out", &exl3_linear_hopper_out, "full EXL3 linear into caller-owned buffers");
  m.def("exl3_linear_hopper", &exl3_linear_hopper, "full EXL3 linear, allocating");
  m.def("exl3_linear_hopper_multi_out", &exl3_linear_hopper_multi_out,
        "fused group of EXL3 linears sharing the input (q/k/v, gate/up): 2 launches for the whole group");
  m.def("init_device", &init_device, "allocate per-device state (locks, fp32 reduce scratch)");
  m.def("set_blocks_per_sm", &set_blocks_per_sm, "tuning knob: co-resident thread blocks per SM (default 1)");
  m.def("set_out_had_inlaunch", &set_out_had_inlaunch,
        "knob: output Hadamard inside the GEMM launch (default) or as a separate launch; same bits either way");
  m.def("set_in_had_inlaunch", &set_in_had_inlaunch,
        "knob (experimental, default off): input Hadamard as the prologue of a cooperative GEMM launch");
  m.def("set_had_warps", &set_had_warps, "knob: 128-blocks per thread block of the Hadamard launches at >= 32 rows (8 default, 1)");
  m.def("set_debug_flags", &set_debug_flags, "timing probes only: 4 = GEMM kernels return immediately (launch floor)");
  m.def("device_info", &device_info, "[SM count, max shared memory per block, max co-resident 256-thread blocks per SM]");
}
